# @package _global_

defaults:
  - rv_1: Normal1
  - rv_2: Normal2

distribution:
  _target_: minde.libs.mixed_rv.MixedBernoulli
  rv_1: ${rv_1}
  rv_2: ${rv_2}
  p: 0.5 # Probability of drawing rv_1

distribution_key: Mixed__rv_1=${rv_1._target_}__rv_2=${rv_2._target_}__p=${distribution.p}

hydra:
  sweeper:
    params:
      # To use different dimensionalities.
      #++distribution.X_dim: ${default_grid.dimensionality}
      #++distribution.Y_dim: ${default_grid.dimensionality}
      # To use shared dimensionality.
      ++dimensionality: ${default_grid.dimensionality}