n_runs: 1
seed: 42
to_be_seeded:
  - basic
  - numpy
  - torch

default_grid:
  mutual_information: range(0.0, 11.0)
  single_value: 1.0
  dimensionality: 3

hydra:
  mode: MULTIRUN
  sweep:
    dir: outputs/${now:%Y-%m-%d}
    subdir: ${estimator._target_}/${distribution._target_}/model=${estimator.args.model.arch}/type=${estimator.args.inference.type}/${distribution_key}/N=${n_samples}/n_runs=${n_runs}/target_mutinfo=${distribution.base_rv.mutual_information}/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}
  sweeper:
    max_batch_size: 100 # Makes startup faster, see https://github.com/facebookresearch/hydra/issues/1324.
    params:
      ++distribution.base_rv.mutual_information: ${default_grid.single_value}
      ++n_samples: 100000
      ++estimator.args.inference.type: c
      ++single_sample_dataset: True