n_runs: 10
seed: 42
to_be_seeded:
  - basic
  - numpy
  - torch

default_grid:
  #mutual_information: 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 10.0
  dimensionality: range(4, 5)

hydra:
  mode: MULTIRUN
  sweep:
    dir: outputs/${now:%Y-%m-%d}
    subdir: ${estimator._target_}/${distribution._target_}/model=${estimator.args.model.arch}/type=${estimator.args.inference.type}/${distribution_key}/N=${n_samples}/n_runs=${n_runs}/target_mutinfo=${distribution.base_rv.mutual_information}/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}
  sweeper:
    max_batch_size: 100 # Makes startup faster, see https://github.com/facebookresearch/hydra/issues/1324.
    params:
      ++distribution.base_rv.mutual_information: 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 10.0
      ++n_samples: 10000
      ++estimator.args.inference.type: j, c