# @package _global_

estimator:
  _target_: minde.minde.MINDE
  args:
    model:
      arch: "conv" # "conv"
      use_ema: True
      preprocessing: "rescale"
      hidden_dim: null
    training:
      lr: 0.01
      bs: 512
      max_epochs: 500
      test_epoch: 50
      nb_workers: 8
      accelerator: "gpu"
      warmup_epochs: 0
      check_val_every_n_epoch: 50
      checkpoint_dir: "minde/checkpoints"
      devices: 1
    inference:
      type: "j"
      mc_iter: 10
      importance_sampling: False
      sigma: 1.0
