# @package _global_

estimator:
  _target_: minde.minde.MINDE
  args:
    log_example_images: True
    return_denoised: True
    model:
      arch: "unet"
      use_ema: True
      preprocessing: "rescale"
      hidden_dim: 6
      norm_num_groups: 2
    training:
      lr: 1e-4
      bs: 512
      max_steps: 1000000
      val_check_interval: 5000
      test_epoch: 5000
      nb_workers: 8
      accelerator: "gpu"
      warmup_epochs: 0
      checkpoint_dir: "minde/checkpoints_unet"
      devices: [2]
    inference:
      type: "c"
      mc_iter: 10
      importance_sampling: True
      sigma: 1.0
      bs: 512
      generate_samples: True
