# @package _global_

estimator:
  _target_: minde.minde.MINDE
  args:
    log_example_images: False
    return_denoised: False
    model:
      arch: "mlp" # "conv"
      use_ema: True
      preprocessing: "rescale"
      hidden_dim: 32
    training:
      lr: 1e-2
      bs: 512
      max_epochs: 500
      test_epoch: 50
      nb_workers: 8
      accelerator: "gpu"
      warmup_epochs: 0
      check_val_every_n_epoch: 50
      checkpoint_dir: "minde/checkpoints_mlp"
      devices: 1
    inference:
      type: "j"
      mc_iter: 10
      importance_sampling: False
      sigma: 1.0
      bs: 512
      generate_samples: False
