# @package _global_

estimator:
  _target_: minde.minde.MINDE
  args:
    log_example_images: True
    return_denoised: True
    checkpoint_path: "/home/foresti/minde/minde/evaluate/minde/checkpoints_unet/lightning_logs/version_234_correct_generation_rectangles/checkpoints/epoch=9999-step=200000.ckpt"
    model:
      arch: "unet"
      use_ema: True
      preprocessing: "rescale"
      hidden_dim: 32
    training:
      lr: 1e-5
      bs: 512
      max_epochs: 10000
      test_epoch: 500
      nb_workers: 8
      accelerator: "gpu"
      warmup_epochs: 0
      check_val_every_n_epoch: 500
      checkpoint_dir: "minde/checkpoints_unet"
      devices: 1
    inference:
      type: "c"
      mc_iter: 10
      importance_sampling: False
      sigma: 1.0
      bs: 512
      generate_samples: True
      checkpoint_dir: "minde/inference/checkpoints_unet"
