# @package _global_

estimator:
  _target_: minde.minde.MINDE
  args:
    log_example_images: False
    return_denoised: False
    model:
      arch: "mlp"
      use_ema: True
      preprocessing: "rescale"
      hidden_dim: 32
    training:
      lr: 1e-2
      bs: 512
      max_steps: 10000
      nb_workers: 8
      accelerator: "gpu"
      warmup_epochs: 0
      val_check_interval: 500
      checkpoint_dir: "minde/checkpoints_mlp"
      devices: [4]
    inference:
      type: "c"
      mc_iter: 10
      importance_sampling: True
      sigma: 1.0
      bs: 512
      generate_samples: False
