# @package _global_

estimator:
  _target_: minde.minde.MINDE
  args:
    log_example_images: True
    return_denoised: True
    model:
      arch: "unet"
      use_ema: True
      preprocessing: "rescale"
      hidden_dim: 8
    training:
      lr: 1e-5
      bs: 512
      max_steps: 100000
      test_epoch: 5000
      nb_workers: 8
      accelerator: "gpu"
      warmup_epochs: 0
      val_check_interval: 5000
      checkpoint_dir: "minde/checkpoints_unet"
      devices: 1
    inference:
      type: "j"
      mc_iter: 10
      importance_sampling: False
      sigma: 1.0
      bs: 512
      generate_samples: True
